### ISSUE TITLE
Generalization of the data generation process

### ISSUE THREAD

**Issue by dachafra** [oeg-upm/gtfs-bench#102]
Develop  a tool taking as input configuration and CSV files at scale and generate the corresponding files and schemas in each desirable format with the corresponding mapping

**Comment by dachafra** [comment]
working in branch develop#102

**Comment by daniel-dona** [comment]
Mapping generator added: https://github.com/oeg-upm/gtfs-bench/pull/105

**Comment by dachafra** [comment]
finished
