### ISSUE TITLE
Clean repository

### ISSUE THREAD

**Issue by dachafra** [oeg-upm/gtfs-bench#113]

**Comment by daniel-dona** [comment]
Work in progress...

**Comment by dachafra** [comment]
readme cleaned 🧹

**Comment by dachafra** [comment]
I'm going to move all the part related to the experimentation of the paper to a new branch.

**Comment by dachafra** [comment]
The new branch: https://github.com/oeg-upm/gtfs-bench/tree/evaluation-jows2020

Now it's time to clean the master one, leaving only the custom generator available.

**Comment by dachafra** [comment]
Steps for cleaning repository:

- [ ] Go folder by folder removing unnecessary files @daniel-dona 
- [ ] Remove RDF generation with SDM-RDFizer from generator @daniel-dona 
- [ ] Remove MySQL and MongoDB deployment by @daniel-dona 
- [ ] Add ShapePoint TriplesMap for generator and edit shapes TriplesMap according to the current ones @daniel-dona 
- [ ] Improve main README.md and describe the content from mappings folder @dachafra 
- [ ] Improve description of the output from the generation @dachafra

**Comment by dachafra** [comment]
In the python script, we also have to remove the "default" values of the data scales and don't give that possibility to the potential users.

**Comment by dachafra** [comment]
Automatic building of the docker image from the benchmark using GitHub actions has been also included

**Comment by daniel-dona** [comment]
The most precise way to present the output structure is a filesystem tree like this:

```
.
├── datasets
│   ├── 1
│   │   ├── sql
│   │   │   ├── AGENCY.csv
│   │   │   ├── CALENDAR.csv
│   │   │   ├── CALENDAR_DATES.csv
│   │   │   ├── FEED_INFO.csv
│   │   │   ├── FREQUENCIES.csv
│   │   │   ├── ROUTES.csv
│   │   │   ├── SHAPES.csv
│   │   │   ├── STOPS.csv
│   │   │   ├── STOP_TIMES.csv
│   │   │   └── TRIPS.csv
│   │   └── xml
│   │       ├── AGENCY.xml
│   │       ├── CALENDAR_DATES.xml
│   │       ├── CALENDAR.xml
│   │       ├── FEED_INFO.xml
│   │       ├── FREQUENCIES.xml
│   │       ├── ROUTES.xml
│   │       ├── SHAPES.xml
│   │       ├── STOPS.xml
│   │       ├── STOP_TIMES.xml
│   │       └── TRIPS.xml
│   ├── 2
│   │   ├── sql
│   │   │   ├── AGENCY.csv
│   │   │   ├── CALENDAR.csv
│   │   │   ├── CALENDAR_DATES.csv
│   │   │   ├── FEED_INFO.csv
│   │   │   ├── FREQUENCIES.csv
│   │   │   ├── ROUTES.csv
│   │   │   ├── SHAPES.csv
│   │   │   ├── STOPS.csv
│   │   │   ├── STOP_TIMES.csv
│   │   │   └── TRIPS.csv
│   │   └── xml
│   │       ├── AGENCY.xml
│   │       ├── CALENDAR_DATES.xml
│   │       ├── CALENDAR.xml
│   │       ├── FEED_INFO.xml
│   │       ├── FREQUENCIES.xml
│   │       ├── ROUTES.xml
│   │       ├── SHAPES.xml
│   │       ├── STOPS.xml
│   │       ├── STOP_TIMES.xml
│   │       └── TRIPS.xml
│   └── 3
│       ├── sql
│       │   ├── AGENCY.csv
│       │   ├── CALENDAR.csv
│       │   ├── CALENDAR_DATES.csv
│       │   ├── FEED_INFO.csv
│       │   ├── FREQUENCIES.csv
│       │   ├── ROUTES.csv
│       │   ├── SHAPES.csv
│       │   ├── STOPS.csv
│       │   ├── STOP_TIMES.csv
│       │   └── TRIPS.csv
│       └── xml
│           ├── AGENCY.xml
│           ├── CALENDAR_DATES.xml
│           ├── CALENDAR.xml
│           ├── FEED_INFO.xml
│           ├── FREQUENCIES.xml
│           ├── ROUTES.xml
│           ├── SHAPES.xml
│           ├── STOPS.xml
│           ├── STOP_TIMES.xml
│           └── TRIPS.xml
├── mappings
│   ├── mapping_sql.nt
│   └── mapping_xml.nt
└── queries
    ├── q10.rq
    ├── q11.rq
    ├── q12.rq
    ├── q13.rq
    ├── q14.rq
    ├── q15.rq
    ├── q16.rq
    ├── q17.rq
    ├── q18.rq
    ├── q1.rq
    ├── q2.rq
    ├── q3.rq
    ├── q4.rq
    ├── q5.rq
    ├── q6.rq
    ├── q7.rq
    ├── q8.rq
    └── q9.rq
```

**Comment by daniel-dona** [comment]
Including a database schema in the MySQL distribution (or custom distribution that include some MySQL table) is possible. The code is already there, It was used to the deployment part that we finally removed. 

Is this of interest @dachafra ?

**Comment by dachafra** [comment]
We don't provide support for the deployment part, we provide the resources and in any case, we could add some "docker-compose" template that could be used for the deployment, but including that step in the generator is not necessary IMO
