### ISSUE TITLE
XML mapping doesn't define  iterator.

### ISSUE THREAD

**Issue by FrankBorrero** [oeg-upm/gtfs-bench#116]
I have been using the benchmark to generate some source  data, as also the mapping files.

When im using XML sourcefiles, im getting this  error: 
Semantifying KGcountry...
TM: http://mapping.example.com/map_shapes_0
The attribute shape_id is missing. 

It seems generator  is not defining  the iterator. 
So when running SDMFizer locally with the generated mapping knowledge graph is not getting created.

**Comment by daniel-dona** [comment]
I'm generating a new docker image for testing right now

**Comment by FrankBorrero** [comment]
Thanks, Please let me know when  i can update my docker.

**Comment by dachafra** [comment]
please @FrankBorrero test it and tell us if this has been solved

**Comment by FrankBorrero** [comment]
Hi,  @dachafra @daniel-dona  docker repository is not updated yet.

**Comment by FrankBorrero** [comment]
I have try the new mapping with RocketRML and  it generates the graph.
Will close issue.
Thanks.
