### ISSUE TITLE
Knowledge Graph generetated with mapping from generator  has problem in properties

### ISSUE THREAD

**Issue by FrankBorrero** [oeg-upm/gtfs-bench#118]
KG is generated wrong, it has some  mistakes in properties.
For example:
<http://transport.linkeddata.es/madrid/agency/00000000000000000001> <http://xmlns.com/foaf/0.1/phone> "00000000000000000001".
<http://transport.linkeddata.es/madrid/agency/00000000000000000001> <http://vocab.gtfs.org/terms#fareUrl> "00000000000000000001".
<http://transport.linkeddata.es/madrid/agency/00000000000000000001> <http://vocab.gtfs.org/terms#timeZone> "00000000000000000001".
<http://transport.linkeddata.es/madrid/agency/00000000000000000001> <http://purl.org/dc/terms/language> "00000000000000000001".
<http://transport.linkeddata.es/madrid/agency/00000000000000000001> <http://xmlns.com/foaf/0.1/name> "00000000000000000001".
<http://transport.linkeddata.es/madrid/agency/00000000000000000001> <http://xmlns.com/foaf/0.1/page> "00000000000000000001".

For the class agency00000000000000000001, the property page is  shown as an String.. in  foaf vocabulary ,
foaf:page is related to a document, not to a string., 
As there are many other properties happening the same situation.
This means that the correct data is not available to evaluate  accurracy from  knowledge graphs generated.

**Comment by dachafra** [comment]
using the fixed-column property in vig this should be resolved. Check all the values from each source that have uri or boolean and put them in that configuration file

**Comment by daniel-dona** [comment]
> using the fixed-column property in vig this should be resolved. Check all the values from each source that have uri or boolean and put them in that configuration file

I don't get it, isn't this a mapping problem?

**Comment by dachafra** [comment]
no, are the unsupported datatypes of VIG (e.g, something is a URI), for solving it one can use fixed-columns in the config file of the engine: https://github.com/oeg-upm/gtfs-bench/blob/master/generation/resources/configuration.conf#L8

**Comment by dachafra** [comment]
the URL-based columns of the GTFS datasets (AGENCY.agency_url STOPS.stop_url ROUTES.route_url FEED.feed_publisher_url) have been added to the "fix" property of VIG.  Issue solved
