### ISSUE TITLE
Check 10-json and 10-xml datasets

### ISSUE THREAD

**Issue by marioscrock** [oeg-upm/gtfs-bench#120]
Applying the mappings to the 10-xml and 10-json datasets (the ones provided [in the repo](https://github.com/oeg-upm/gtfs-bench/blob/master/data/data-url.csv)) I obtain a different number of triples w.r.t. the ones obtained from 10-csv lifting. The same does not happen for other sizes (e.g. 5-csv, 5-json, 5-xml produce the same number of triples).

Given that the mappings used are the same for every size I think there could be a problem in the datasets. The number of records is correct (number of Record nodes in JSON/XML files is the same as the number of rows in the CSV files), so my guess is that there are some identifiers used for the joins in RML that are not correct in all the JSON/XML files of the 10-json/xml datasets.

**Comment by dachafra** [comment]
@daniel-dona could you analyse if the generator produces exactly the same problem?

**Comment by dachafra** [comment]
using the current generator, this issue has been solved!
