### ISSUE TITLE
Improve generator's documentation

### ISSUE THREAD

**Issue by dachafra** [oeg-upm/gtfs-bench#121]
Improve the current documentation of the generator's output with:

- [x] explanation of the output folders and how they are organized
- [x] docker-compose template to provide the support to deploy different instances of the generator's ouput

**Comment by dachafra** [comment]
we should remove this line from the generator: https://github.com/oeg-upm/gtfs-bench/blob/master/composer/app.py#L649

**Comment by daniel-dona** [comment]
> we should remove this line from the generator: https://github.com/oeg-upm/gtfs-bench/blob/master/composer/app.py#L649

Fixed!

**Comment by dachafra** [comment]
@daniel-dona can we also remove this folder? https://github.com/oeg-upm/gtfs-bench/tree/master/semantify

**Comment by dachafra** [comment]
the documentation has been updated, the rest will be done asap
