### ISSUE TITLE
Docker "--pull always" option

### ISSUE THREAD

**Issue by daniel-dona** [oeg-upm/gtfs-bench#123]
The "--pull" option seems to be officially documented:

https://docs.docker.com/engine/reference/commandline/run/#options

...but is not available on older versions of Docker

The first release where it's implemented is 20.10, currently the last one.

https://github.com/docker/cli/pull/1498#issuecomment-617805222

Maybe a fall-back option can be documented

**Comment by dachafra** [comment]
what would be the other option? two commands? pull and then run?

**Comment by daniel-dona** [comment]
> what would be the other option? two commands? pull and then run?

Exactly that 

```
docker pull oegdataintegration/gtfs-bench
docker run -itv "$(pwd)":/output oegdataintegration/gtfs-bench
```

**Comment by dachafra** [comment]
okey!
