### ISSUE TITLE
Improve output data compression

### ISSUE THREAD

**Issue by daniel-dona** [oeg-upm/gtfs-bench#124]
At large scale (>1000) the compression of the final result archive is notably slow. By default gzip is a single thread program and can't use the parallelization benefits of modern computers. 

A different implementation of gzip algorithm is pigz, but is only parallel for compression, not decompression. Another one is pugz (https://github.com/Piezoid/pugz) that seams parallel in both ways.

On the other hand, better compression ratios can be achieved using other algorithms as bzip2 or xz (lzma2).

**Comment by daniel-dona** [comment]
The output compression format (`zip`, `tar.bz2` or `tar.xz`) can be an option of the user interface. If the output is just one format it should be `zip` as its the most used and compatible.

What do you think @dachafra?

On the other hand, `pugz` is only an option for `gzip`, but `gzip` and `zip` are different formats. So, pugz is discarded and I have to search for an alternative...

**Comment by dachafra** [comment]
I wouldn't delegate the compression option to the user sincerely. 
Let's prioritize the performance on obtaining the resources instead of the compression format

**Comment by dachafra** [comment]
btw, I found this: https://github.com/dcwatson/deflate

**Comment by daniel-dona** [comment]
> btw, I found this: https://github.com/dcwatson/deflate

But that is only the `gzip` and `zip` compression algorithm, the interesting thing is if there is a parallel implementation, and for the moment it seams is not possible. 

We can move to `tar.xz`, is compatible with 7-zip on Windows. Is the best option in speed, size and compatibility.

**Comment by dachafra** [comment]
100% agree, tar.xz is perfect!

**Comment by daniel-dona** [comment]
Some numbers in a machine with 24 computing threads.

Using zip [compression level 9]:
```
real	5m58.036s
user	5m55.845s
sys	0m2.000s
```

Using tar + pxz [compression level 1]:

```
real	0m30.468s
user	8m39.010s
sys	0m18.165s
```

For a similar output size:
```
-rw-r--r-- 1 root root 611M Jun 14 11:25 result.tar.xz
-rw-r--r-- 1 root root 652M Jun 14 11:15 result.zip
```

Better compression ratios can be achieved, but I think the problem is not the size but the compression time.

**Comment by dachafra** [comment]
No problem with the size! Awesome results, perfect :-D

**Comment by dachafra** [comment]
tested and working! clossing issue :-D
