### ISSUE TITLE
url fixed columns are not mantained in the scaling-up with VIG

### ISSUE THREAD

**Issue by jatoledo** [oeg-upm/gtfs-bench#127]
to check what happens with the AGENCY.agency_url STOPS.stop_url ROUTES.route_url FEED.feed_publisher_url as VIG is not maintaining the input values from the original sources, hence, the columns are not url and engines report a error

**Comment by dachafra** [comment]
seems that from 1.8.0 to 1.8.1 the property has changed from` pumper-type` to `mode`. 
We should perform some tests locally with VIG to observe how it works

**Comment by dachafra** [comment]
SOLVED AT: https://github.com/oeg-dataintegration/vig
The problem was in the VIG code, bc they removed the fixed columns from the configuration
