### ISSUE TITLE
Mappings producing different number of results

### ISSUE THREAD

**Issue by ArenasGuerreroJulian** [oeg-upm/gtfs-bench#132]
**Describe the bug**
For GTFS-1-CSV, the current mappings of the generator produce a different number of results (339114) w.r.t. the ones used in https://github.com/oeg-upm/kgc-eval/tree/master/mappings (397622).

**Comment by dachafra** [comment]
The correct number of results is 395953 not 397622

**Comment by daniel-dona** [comment]
> The correct number of results is 395953 not 397622

I'm getting 455441 using rdfizer :/

**Comment by daniel-dona** [comment]
At least I'm getting the same number of triples after this fix: https://github.com/oeg-upm/gtfs-bench/commit/d2251950c5aa7f45bd19eb221c90504fd23adb06

Can you confirm @ArenasGuerreroJulian ?

**Comment by dachafra** [comment]
we have changed the generator, so it would be possible that the number of triples changes, although it shouldn't...

**Comment by ArenasGuerreroJulian** [comment]
I am not getting results, its is killing the memory @daniel-dona . But I am getting different number of POMs with respect to former mappings

**Comment by daniel-dona** [comment]
> I am not getting results, its is killing the memory @daniel-dona . But I am getting different number of POMs with respect to former mappings

That's strange, what tool are you using?

**Comment by dachafra** [comment]
Bug found in the generated mapping:
Shape_points TriplesMap only contains 2 POM (class and lat)

Missing these ones:
```
      - [geo:long,$(shape_pt_lon),xsd:double]     
      - [gtfs:pointSequence,$(shape_pt_sequence)]      
      - [gtfs:distanceTraveled,$(shape_dist_traveled)]
```

**Comment by dachafra** [comment]
after some checks, seems shapes are ok! So only that shape_points issue ;-)

**Comment by dachafra** [comment]
solved!
