### ISSUE TITLE
Change template in CalendarDateRule subject IRI

### ISSUE THREAD

**Issue by marioscrock** [oeg-upm/gtfs-bench#93]
[L176](https://github.com/oeg-upm/gtfs-bench/blob/b98243582180f4b956e856c2d7a43f5cd3efae3a/mappings/gtfs-csv.yml#L176)  The subject IRI composed using only `service_id` is wrong within the file `calendar_dates`. Also `date` should be used to generate unique IRIs.

**Comment by dachafra** [comment]
This will be resolved during Christmas time

**Comment by dachafra** [comment]
solved
