### ISSUE TITLE
Add function to process exception_type in calendar_dates GTFS file

### ISSUE THREAD

**Issue by marioscrock** [oeg-upm/gtfs-bench#94]
[L180](https://github.com/oeg-upm/gtfs-bench/blob/b98243582180f4b956e856c2d7a43f5cd3efae3a/mappings/gtfs-csv.yml#L180) `exception_type` is not of boolean type since it uses 1 and 2 as values in GTFS. This can cause mixed boolean/string values (1 is converted, 2 no). A function is required during lifting to match gtfs:dateAddition range as boolean or the input files should be changed accordingly.

**Comment by dachafra** [comment]
This issue shouldn't be part of the Knowledge Graph Generation process as it is currently out of the scope of the benchmark, it should be achieved in a pre-processing task of the date (only for original data, gtfs-1)

**Comment by dachafra** [comment]
to be tested in the generation process by morph-csv + vig

**Comment by dachafra** [comment]
@daniel-dona could you include this change in the new SQL dump for VIG?

**Comment by dachafra** [comment]
solved for `exception_type` in the new generator software
