### ISSUE TITLE
Fix column names in mappings

### ISSUE THREAD

**Issue by marioscrock** [oeg-upm/gtfs-bench#95]
- [x] [L203](https://github.com/oeg-upm/gtfs-bench/blob/3228c0a1cd725c5775cf90a362dd0f81c49cca66/mappings/gtfs-csv.yml#L203) In the GTFS specification the field is called `feed_publisher_url`. Change `feed_published_url` to `feed_publisher_url`.
- [x] [L217](https://github.com/oeg-upm/gtfs-bench/blob/b98243582180f4b956e856c2d7a43f5cd3efae3a/mappings/gtfs-csv.yml#L217) In the GTFS specification the field is called `shape_dist_traveled`. However, the datasets provided in the Madrid-Bench use `shape_dist` so this should not be an issue.

**Comment by dachafra** [comment]
the second one is not an issue as it is under control of the benchmark, issue fixed and closed
