### ISSUE TITLE
Script for the materialization

### ISSUE THREAD

**Issue by dachafra** [oeg-upm/gtfs-bench#99]
Prepare a script that getting the results from VIG in CSV generates the RDF using the RDFIzer and the RML mapping

**Comment by dachafra** [comment]
if you create the service to run the sdm-rdfizer, this step would be very easy  ;-)

**Comment by dachafra** [comment]
@daniel-dona this could be an improvement in the generation step, additionally to the mapping and sources for the evaluation, we can use the SDM-RDFizer to generate the baseline RDF using the CSVs from VIG

**Comment by dachafra** [comment]
should be optional!

**Comment by dachafra** [comment]
can we close this? @daniel-dona

**Comment by dachafra** [comment]
done by @daniel-dona

**Comment by daniel-dona** [comment]
Not done yet, my mistake. Pending docker image regeneration...

**Comment by dachafra** [comment]
now yes, done
